version: '3.8'

services:
  db:
    image: postgres:13.0
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    build: ./
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn team_finder.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    restart: always

volumes:
  pg_data: