# backend/constants.py

# Pagination
PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

# Autocomplete
SKILLS_AUTOCOMPLETE_LIMIT = 10

# Project statuses
PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'

# Avatar generation
AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 120
AVATAR_TEXT_COLOR = (255, 255, 255)
AVATAR_COLOR_MIN = 50
AVATAR_COLOR_MAX = 200

# Field lengths
MAX_LENGTH_NAME = 124
MAX_LENGTH_ABOUT = 256
MAX_LENGTH_PHONE = 12
MAX_LENGTH_PROJECT_NAME = 200
MAX_LENGTH_STATUS = 6
